[options]
db_host = localhost
db_user = odoouser
db_password = kojiodoo
db_name = odoodata
xmlrpc_port = 8069
addons_path = odoo/addons,addons,muk_web_theme,base_accounting_kit,clear_data,myaddons
admin_passwd = $pbkdf2-sha512$600000$W4sxBsAYIyQkpPS.V4pRqg$lIvsGrAc99ad5STfQNgs.hd1Esmf7KHV./w4ebaPwPqA1.lBrE/xezi5em.UpB.rZoiUj0mFF6pbnKwZsQPOdA
without_demo = all
